octokit/source-generator

- .github/workflows/build-csharp.yml
- .github/workflows/build-go.yml
- .gitignore
- README.md
- generated/csharp/.vscode/launch.json
- generated/csharp/.vscode/tasks.json
- generated/csharp/Program.cs
- generated/csharp/csharp.csproj
- post-processors/go/main.go
When working on #10, I came across build errors due to Kiota releasing their v1.0 major version. This PR:
- pins to a specific Kiota version (instead of installing the latest each time)
- bumps Kiota's Go dependency versions
- adds additional hacks to get Go compilation working again with the old hand-edited spec
- fixes the .NET generation and build process to work with the new major version of Kiota
Re: these hacks, at some point in the near future of generative SDK work they will need to be codified and solved for real, whether that's simply filtering out the broken endpoints, working with Kiota upstream, or discovering as-yet-hidden spec errors. However, I believe that's a task for another day given our current focus on the OpenAPI spec and linting. 
Note that running the sample .NET …
> Fix old spec processing

- .github/workflows/build-csharp.yml
- .github/workflows/build-go.yml
- .gitignore
- README.md
- generated/csharp/Program.cs
- generated/go/main.go
- post-processors/go/main.go
Our sample app in Go was non-existent and in C# it was non-building. This PR fixes both of those issues. 
The Go sample app has a commented-out section I've manually tested works to retrieve private user profile information when appropriate auth creds are provided.
> Clean up sample applications

- post-processors/go/main.go
Fixes #15. It's not actually a race condition causing this, but something in Kiota being non-deterministic. This is another issue we should take to their team. I've filed #28 so we can remember to do that.
> fix: Workaround to fix Kiota non-determinism resulting in flaky builds

- scripts/generate-csharp.sh
- scripts/generate-go.sh
Sourcing the scripts will load functionality from them but not execute it. This small update causes the `install-tools.sh` script's code to be executed. Another way to do this would be to refactor the script to export a function and then call that function in each parent script; I've elected to go this way because it's fewer lines but I'm happy to change that as desired. 
On this branch:
```
sh$ ./scripts/generate-go.sh
The correct version (1.8.1) of microsoft.openapi.kiota is installed...skipping install step
+ go run schemas/main.go --schema-next=false
2023/11/07 11:00:00 Downloading latest schema from descriptions directory
```
On main:
```
sh$ ./scripts/generate-go.sh
./scripts/generate-go.sh: 10: source: not found
+ go run schemas/main.go --schema-next=false
```
I'm not sure why my …
> Call the scripts instead of sourcing them

- post-processors/go/main.go
Fixes #17. 
Instead of hard-coding dependencies and their versions, this PR uses the `kiota list` command to get them. 
:warning: **Note:** :warning: in a very "production" application, this should use structs rather than interface{}s and it should be unit-tested, which it's not currently. @nickfloyd do you think we're at an appropriate stage where I should sharpen it like so? Is this just me being lazy? Are we in enough flux that I shouldn't do so yet and instead file an issue to tackle it after the alpha release?
> Use kiota list command to install dependencies

- .github/workflows/build-go.yml
- post-processors/go/main.go
- scripts/generate-go.sh
Making our first committed version of the code required a few small changes. Our post-processing has been updated, and changes to the build script and Action ensure a foundation for auto-updating the generated code in a future PR.
> Code changes used for first draft of code generation

- .github/workflows/build-go.yml
- post-processors/go/main.go
- scripts/install-tools.sh
Fixes #22 (thanks @baywet!) https://github.com/microsoft/kiota/issues/3637 has been fixed and so we can bump our Kiota version and remove a post-processor workaround.
> Bump Kiota to v1.8.2

- .github/workflows/build-csharp.yml
- .github/workflows/build-go.yml
This PR uses the `gr2m/create-or-update-pull-request-action@cd-path` Action to autogenerate commits to the octokit/dotnet-sdk repo.
> Auto-update the dotnet SDK

- scripts/generate-csharp.sh
Since the SDK get's built on the CI step - the script that is used to generate the C# version of the SDK should no longer have a build step.  The project was moved from the generator and put in the dotnet-sdk.
> maint: Removes the unused part of the generate script

- .github/workflows/build-csharp.yml
- .github/workflows/build-go.yml
- scripts/generate-csharp.sh
- scripts/generate-go.sh
Vincent mentioned we can use the `--ebc` flag, which excludes backwards compatibility from a breaking change Kiota made a while back. This will result in big changes (technically breaking, though we haven't provided any guarantees for users) and result in a lot less code, which is nice.
> Use --ebc on all generation runs

- .vscode/launch.json
- post-processors/csharp/main.go
- post-processors/go/main.go
- scripts/install-tools.sh
When looking at the dotnet-sdk this morning, I noticed we hadn't seen a new update recently. I checked the [source-generator's Actions](https://github.com/octokit/source-generator/actions) and saw both Go and .NET generation has been broken for about a week. 
This PR adds workarounds that fix (hopefully temporary) breakages in Kiota. Next I need to file issues for these problems.
> Build fixes

- .github/workflows/build-csharp.yml
- .github/workflows/build-go.yml
- scripts/install-tools.sh
We've been running into a lot of errors and failed builds recently driven by using prerelease builds of Kiota. In order to stabilize our CI process and ensure timely delivery of new SDKs, let's switch to using regular builds of Kiota.
> Don't use prerelease versions of Kiota

- .vscode/launch.json
- post-processors/csharp/main.go
- stage/dotnet-sdk/src/GitHub.Octokit.SDK.csproj
When troubleshooting the Kiota upgrade, I noticed [.NET builds](https://github.com/octokit/source-generator/actions/runs/9491596031/job/26157323607) were erroneously succeeding. We were seeing output like `chdir /home/runner/work/source-generator/source-generator/../dotnet-sdk/src: no such file or directory`. 
This fixes that path (and a couple other instances I found) to use the new staging locations. The .csproj changes are purely a result of rerunning `scripts/generate-dotnet.sh` with Kiota v1.14.0 installed, so IMO they're worth keeping.
> Remove additional uses of relative paths

- stage/dotnet-sdk/README.md
This PR replays https://github.com/octokit/dotnet-sdk/pull/89 in the source-generator. I noticed when reviewing https://github.com/octokit/dotnet-sdk/pull/90 that those changes were going to be undone. 
In the future once this architecture is more fully fleshed out, we'll have to be more careful with our documentation so contributors (including ourselves) understand the relationship between the repositories and know where to make changes appropriately.
> Fix dotnet-sdk sample

- .github/workflows/build-dotnet.yml
- .github/workflows/build-go.yml
Fix for the issue breaking PRs we're seeing [here](https://github.com/octokit/source-generator/actions/runs/9865896920/job/27243696681#step:9:69) and [here](https://github.com/octokit/source-generator/actions/runs/9866081156/job/27244216071#step:8:1), for example.
Actions doesn't automatically pass environment variables to reusable workflows, which is causing PR creation to 404.
> REPO_NAME env var fix

- stage/dotnet/dotnet-sdk-enterprise-cloud/README.md
- stage/dotnet/dotnet-sdk-enterprise-server/README.md
- stage/dotnet/dotnet-sdk/README.md
- stage/go/go-sdk-enterprise-cloud/README.md
- stage/go/go-sdk-enterprise-server/README.md
- stage/go/go-sdk/README.md
Issues like https://github.com/octokit/dotnet-sdk/issues/100 are the result of a simple misunderstanding between SDK offerings. This small README update attempts to clarify that by noting Octokit.net and its differences before linking to our reasoning for why we're building a generated SDK.
> Note octokit.net in READMEs

- .github/workflows/build-dotnet.yml
- .github/workflows/build-go.yml
We've been seeing EPERM errors on branch updates for dotnet-sdk-enterprise-server. This was due to a mistake in the way the branch was being created locally: since the check was only seeing the branch not existing locally, not on the remote, a new branch was always being created from the main branch. When fetching that branch from the remote and trying to replay those changes on top of the locally created branch, conflicts arose. 
This PR should fix those changes, as demonstrated by a failing build in [.NET here](https://github.com/octokit/source-generator/actions/runs/10099817943) followed by a successful [.NET build here](https://github.com/octokit/source-generator/actions/runs/10102017040) and a successful Go build [here](https://github.com/octokit/source-generator/actions/runs/10102015 …
> Fix branch update permissions errors

- stage/go/go-sdk-enterprise-cloud/pkg/client.go
- stage/go/go-sdk-enterprise-server/pkg/client.go
- stage/go/go-sdk/pkg/client.go
See https://github.com/octokit/go-sdk/issues/90 and https://github.com/microsoft/kiota/issues/4995. 
(Hopefully temporary) fix that affects organization custom properties (and possibly other unknown endpoints). Kiota default middleware enables gzipped payloads, which GitHub's API doesn't always accept (and may return a 400 instead of a more correct 415). This small PR turns that off for our Go SDKs.
> (Hopefully temporarily) disable gzipped request payloads by default

- scripts/generate-dotnet.sh
- stage/dotnet/dotnet-sdk-enterprise-server/.github/workflows/add_to_octokit_project.yml
- stage/dotnet/dotnet-sdk-enterprise-server/.github/workflows/build.yml
- stage/dotnet/dotnet-sdk-enterprise-server/.github/workflows/immediate-response.yml
- stage/dotnet/dotnet-sdk-enterprise-server/.github/workflows/publish.yml
Note: these changes are intentionally static; the platform version numbers (as branches) are intended to be fixed until we decide otherwise or release a GA where this can be more "fuzzy"
The approach for building and releasing GHES instances of the .NET SDK are as follows:
1. Generation happens when GHES OpenAPI definitions change
2. Generator creates branched based PRs with the new changes
3. `build.yml` fires off on GHES versioned branches in the GHES SDK repo - currently 4x
4. For each branch the push>branches collection is updated to only the version the branch is targeted for: i.e. 3.10...
5. Once validated and merged into each GHES versioned branch manually make a release
6. Release is made for each version which triggers `publish.yml`
7. Nuget pack evaluates the name and version of …
> Adds the build and publish logic for each GHES branch 

- .github/dependabot.yml
- stage/go/go-sdk-enterprise-cloud/.github/dependabot.yml
- stage/go/go-sdk-enterprise-server/.github/dependabot.yml
- stage/go/go-sdk/.github/dependabot.yml
This PR centralizes Dependabot configuration in the source-generator repository. It ignores Kiota dependencies as those are installed using the `kiota` CLI and should not be updated out-of-band. It updates NuGet, Go, and GitHub Actions dependencies across all of source-generator and the downstream SDKs.
> Add dependabot.yml

- .github/dependabot.yml
Dependabot logs can be viewed by going to repo Insights --> Dependency graph --> Dependabot. From there, you can click your ecosystem of choice and view recent logs or manually trigger jobs. Discovering this fact helped me view logs like [this one](https://github.com/octokit/source-generator/actions/runs/10188323278/job/28184258286), which made me realize I mistyped the stage directories when I filled this out in the first place :facepalm: :facepalm: :facepalm:
> Fix stage directories for dependabot runs

- stage/dotnet/dotnet-sdk-enterprise-server/README.md
- stage/dotnet/dotnet-sdk-enterprise-server/cli/Authentication/PersonalAccessToken.cs
- stage/dotnet/dotnet-sdk-enterprise-server/src/Client/RequestAdapter.cs
- stage/dotnet/dotnet-sdk/cli/Authentication/PersonalAccessToken.cs
- stage/dotnet/dotnet-sdk/src/Client/RequestAdapter.cs
- stage/go/go-sdk-enterprise-server/README.md
- stage/go/go-sdk-enterprise-server/pkg/authentication/token_provider_test.go
- stage/go/go-sdk-enterprise-server/pkg/example_test.go
Initial rework of GHES tests to so that a proper default host is used and not the formatter provided by the OpenAPI definitions.
dotcom:
```
servers:
- url: https://api.github.com
```
GHES
```
servers:
- url: "{protocol}://{hostname}/api/v3"
```
GHEC
```
servers:
- url: https://api.github.com
```
We already have an API that allows the setting of baseurl
``` Go
adapter, err := kiotaHttp.NewNetHttpRequestAdapter(tokenProvider)
if err != nil {
log.Fatalf("Error creating request adapter: %v", err)
}
adapter.SetBaseUrl("https://api.github.com")
```
> fix: GHES OpenAPI descriptions have the default host for the API set as a formatter not a URL

- .github/dependabot.yml
Group NuGet Dependabot runs to avoid "too many PRs" failures like this: 
Also link to exact directories where workflows exist in PRs. Dependabot updates for Actions won't run until #76 is merged to add that directory.
> Group NuGet Dependabot runs

- post-processors/csharp/main.go
Starting [Friday](https://github.com/octokit/source-generator/actions/runs/10311495117/job/28545187915), our .NET builds began failing with the following errors: 
```
Error: /home/runner/work/source-generator/source-generator/stage/dotnet/dotnet-sdk/src/GitHub/Orgs/Item/Teams/TeamsRequestBuilder.cs(68,110): error CS0234: The type or namespace name 'GitHub' does not exist in the namespace 'GitHub.Models' (are you missing an assembly reference?) [/home/runner/work/source-generator/source-generator/stage/dotnet/dotnet-sdk/src/GitHub.Octokit.SDK.csproj]
Error: /home/runner/work/source-generator/source-generator/stage/dotnet/dotnet-sdk/src/GitHub/Orgs/Item/Teams/Item/Teams/TeamsRequestBuilder.cs(50,110): error CS0234: The type or namespace name 'GitHub' does not exist in the namespace …
```
> Don't post-process .NET GitHub.Models.Team issues anymore

- stage/dotnet/dotnet-sdk-enterprise-cloud/src/Client/RequestAdapter.cs
- stage/dotnet/dotnet-sdk-enterprise-server/src/Client/RequestAdapter.cs
- stage/dotnet/dotnet-sdk/src/Client/RequestAdapter.cs
Builds are failing still on formatting errors like [this one](https://github.com/octokit/dotnet-sdk/actions/runs/10426487008/job/28879509943?pr=111): 
> /home/runner/work/dotnet-sdk/dotnet-sdk/src/Client/RequestAdapter.cs(33,2): error FINALNEWLINE: Fix final newline. Insert '\n'. [/home/runner/work/dotnet-sdk/dotnet-sdk/src/GitHub.Octokit.SDK.csproj]
I wonder if I have an editor configuration issue, or else there's something wonky going on with the copy step that's removing the whitespace. Locally, I had a newline added at the end of the file, and running `dotnet format --verify-no-changes` succeeded for me. 
However, the PR updates still showed the whitespace removed: 
This PR manually adds it back.
> Add request adapter newlines

- post-processors/csharp/main.go
- post-processors/go/main.go
Fixes https://github.com/octokit/dotnet-sdk/issues/71. 
We have an issue with our specification/a Kiota design decision: Kiota expects the schema to represent the final result of the redirect. Our schema only gives the redirect itself: a Location header with a URL. The best middle ground is probably a mixture of both, in which the schema of the results of the download are described in the 302 response, but Kiota does not parse that right now, and this gets us immediately unblocked. 
I've validated locally that both tarballs and zips can be downloaded in C# and Go using the output of the generated code.
> Fix zipball/tarball downloading issue in C# and Go

- .github/workflows/build-dotnet.yml
- .github/workflows/build-go.yml
According to [this docs page](https://docs.github.com/en/enterprise-server@3.12/admin/all-releases), as of August 8th, GHES 3.14 has been released. As of August 29th, GHES 3.10 has been deprecated. Let's make those changes too!
Sidenote: This catches all instances of 3.10 in the project. Are there other tasks I'm not thinking of? Maybe we need to mark 3.10 as deprecated in Nuget or something?
> Deprecate GHES 3.10 and introduce GHES 3.14

- scripts/install-tools.sh
This will address 3 of our issues with the generated code around discriminators and types
> Updates Microsoft.OpenAPI.Kiota generator tool from v1.18.0 to v1.19.0

- stage/go/go-sdk-enterprise-cloud/pkg/client.go
- stage/go/go-sdk-enterprise-cloud/pkg/client_test.go
- stage/go/go-sdk-enterprise-server/pkg/client.go
- stage/go/go-sdk-enterprise-server/pkg/client_test.go
- stage/go/go-sdk/pkg/client.go
- stage/go/go-sdk/pkg/client_test.go
In testing https://github.com/octokit/go-sdk I found that when using GitHub App authentication, the ghinstallation dependency has a hardcoded `https://api.github.com` for token refreshes. In local development (and I think for Enterprise Server in general) this means that the `WithBaseUrl` option does not take effect when generating an Installation token.
This PR sets the ghinstallation `appTransport.BaseURL` when `WithBaseUrl` is used.
I added a new test using `httptest.NewServer` as I didn't see a good way to reflect on the state of the ghinstallation transport.
In running `./scripts/generate-go.sh ...` I noticed it updated go.mod with some minor version bumps, but I have not included the diffs for go.mod and go.sum -- let me know if those should be included, but there are no new …
> Set BaseURL for ghinstallation for GitHub Apps
